In [7]:
import nltk
from textblob_de import TextBlobDE as TextBlob
import numpy as np

In [1]:
from sa_class import Text_Sentiment # importiert die Klasse für Sentiment Analysis

In [27]:
import json
with open('article_2p9.txt') as json_file:  # importiert Text Datei
    data = json.load(json_file)

In [4]:
ts = Text_Sentiment(data['text'])  # unter Verwendung von der Klasse Text_Sentiment wird der Text des Artikels ausgewählt, damit in weiterer Folge die Sentiments (polarity und subjectivity) ermittelt werden können

In [5]:
ts.text_sentiment()

Sentiment(polarity=0.3587878787878788, subjectivity=0.08333333333333333)

In [29]:
np.array(ts.sentence_sentiments()) # sentiments pro Satz des Textes

array([[ 0.5       ,  0.5       ],
       [ 0.7       ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 1.        ,  0.        ],
       [ 0.7       ,  0.        ],
       [ 1.        ,  0.        ],
       [ 0.7       ,  0.        ],
       [ 1.        ,  0.        ],
       [ 1.        ,  0.        ],
       [ 0.        ,  1.        ],
       [ 0.38333333,  0.        ],
       [ 0.66      ,  0.        ],
       [-1.        ,  0.        ],
       [ 1.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.45      ,  0.33333333],
       [ 0.7       ,  0.        ]])

In [30]:
ts.agg_sentiment() # Mittelwert der Sentiments pro Satz aus Text

array([0.35878788, 0.08333333])

In [17]:
ths = Text_Sentiment(data['thread']) # unter Verwendung der Klasse Text_Sentiment werden die Kommentare (thread) zum Artikels ausgewählt

In [19]:
ths.text_sentiment() # sentiments der gesamten Kommentare

Sentiment(polarity=0.08190188092975556, subjectivity=0.08420120568552623)

In [20]:
np.array(ths.sentence_sentiments()) # sentiments pro Kommentar

array([[1., 0.],
       [0., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
ths.agg_sentiment() # Mittelwert der Sentiments pro Satz aus Text

array([0.08190188, 0.08420121])

In [ ]:
# wenn man den Mittelwert der Sentiments des Textes mit dem MIttelwert der Sentiments der KOmmentare vergleicht, sieht man, dass die Polarity der Kommentare niedriger ist, aber beide positiv. Subjektivität ist nur gering höher bei den Kommentaren