In [2]:
import nltk
from textblob_de import TextBlobDE as TextBlob
import numpy as np



In [3]:
from sa_class import Text_Sentiment # importiert die Klasse für Sentiment Analysis

In [4]:
import json
with open('article_2p9.txt') as json_file:  # importiert Text Datei
    data = json.load(json_file)

In [5]:
ts = Text_Sentiment(data['text'])  # unter Verwendung von der Klasse Text_Sentiment wird der Text des Artikels ausgewählt, damit in weiterer Folge die Sentiments (polarity und subjectivity) ermittelt werden können

In [6]:
ts.text_sentiment()

Sentiment(polarity=-0.006388888888888892, subjectivity=0.06111111111111111)

In [15]:
np.array(ts.sentence_sentiments()) # sentiments pro Satz des Textes

array([[-1.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.7       ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.7       ,  0.        ],
       [ 0.7       ,  0.        ],
       [-1.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.7       ,  0.        ],
       [ 0.7       ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  1.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.175     ,  0.        ],
       [-0.35      ,  0.5       ],
       [ 0.        ,  0.        ],
       [-0.46666667,  0.33333333],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.7       ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,

In [16]:
ts.agg_sentiment() # Mittelwert der Sentiments pro Satz aus Text

array([-0.00638889,  0.06111111])

In [50]:
comment_sentiments = []                                 # für die Kommentare werden die Sentiments pro Kommentar erstellt und als Liste 
for comment in data['thread']:                          # bereitgestellt
    tc = Text_Sentiment(comment)
    comment_sentiments.append(tc.text_sentiment())
np.array(comment_sentiments)

array([[-0.15      ,  0.        ],
       [ 0.35      ,  0.        ],
       [ 0.14      ,  0.4       ],
       [ 0.05      ,  0.33333333],
       [ 0.        ,  0.        ],
       [-0.04666667,  0.2       ],
       [ 0.        ,  0.5       ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.5       ,  0.5       ],
       [-0.14      ,  0.        ],
       [-0.6       ,  0.25      ],
       [ 0.16666667,  0.16666667],
       [-0.1475    ,  0.        ],
       [ 0.56666667,  0.        ],
       [-0.7       ,  0.        ],
       [ 0.62      ,  0.        ],
       [ 0.28      ,  0.        ],
       [-0.35833333,  0.        ],
       [ 0.34      ,  0.1       ],
       [ 0.        ,  0.        ],
       [ 0.2125    ,  0.        ],
       [ 0.2125    ,  0.        ],
       [ 0.        ,  0.25      ],
       [-0.33333333,  0.16666667],
       [ 0.23333333,  0.        ],
       [-0.33333333,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,

In [70]:
np.mean(comment_sentiments, axis=0)                # Mittelwert für comments sentiments

array([-0.00474138,  0.09885057])